name: Build Morpheme Server

on:
  push:
    branches:
      - main
      - "feature/**" # Optional: Build on pushes to any feature branch

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Upload JAR and Dockerfile
        uses: actions/upload-artifact@v4
        with:
          name: mpm-recent-jar
          path: |
            target/mpm-recent.jar
            Dockerfile

  deploy:
    needs: build
    name: Deploy mpm-recent.jar to Toybox
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          ssh-keyscan -t rsa $SSH_HOST_IP >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts
        shell: bash
        env:
          SSH_FINGERPRINT: ${{secrets.SSH_TOYBOX_FP}}
          SSH_PRIVATE_KEY: ${{secrets.SSH_TOYBOX_PRIVATE}}
          SSH_HOST_IP: ${{secrets.SSH_TOYBOX_HOST}}
      - uses: actions/download-artifact@v4
        with:
          name: mpm-recent-jar
      - name: List of Files
        run: ls -alh .
      - name: Sending jar
        run: rsync --archive --verbose --stats mpm-recent.jar ${{secrets.SSH_TOYBOX_DST}}
      - name: Sending Dockerfile
        run: rsync --archive --verbose --stats Dockerfile ${{secrets.SSH_TOYBOX_DST}}
